swagger: "2.0"
info:
  title: Petition manager
  description: Petition manager
  version: 1.0.0
schemes:
  - http

host: localhost:8080

securityDefinitions:
  HeaderToken:
    type: apiKey
    in: header
    name: token

security:
  - HeaderToken : []

tags:
  - name: petitions

paths:
  /petitions:
    post:
      tags:
        - petitions
      operationId: petitionsPost
      summary: Create a new petition
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/petition'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/petition'
    get:
      tags:
        - petitions
      operationId: petitionsGet
      summary: Get all petitions
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/petition'


  /petitions/{petitionId}:
    parameters:
      - in: path
        name: petitionId
        required: true
        type: integer
    put:
      tags:
        - petitions
      operationId: petitionsUpdate
      summary: Update a petition
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/petition'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/petition'
    get:
      tags:
        - petitions
      operationId: petitionsGetById
      summary: Get a petition
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/petition'
    delete:
      tags:
        - petitions
      operationId: petitionsDelete
      summary: Remove a petition
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/petition'



definitions:
  petition:
    type: object
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        description: Name of the petition
        example: Loud neighbors
      body:
        type: string
        description: Body of the petition
        example: My neighbors are very loud
      author_email:
        type: string
        description: Email address of the author of the petition
        example: silent_man@email.com
  principal:
    type: string
