// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPetitionsDeleteParams creates a new PetitionsDeleteParams object
//
// There are no default values defined in the spec.
func NewPetitionsDeleteParams() PetitionsDeleteParams {

	return PetitionsDeleteParams{}
}

// PetitionsDeleteParams contains all the bound params for the petitions delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters petitionsDelete
type PetitionsDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	PetitionID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPetitionsDeleteParams() beforehand.
func (o *PetitionsDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPetitionID, rhkPetitionID, _ := route.Params.GetOK("petitionId")
	if err := o.bindPetitionID(rPetitionID, rhkPetitionID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPetitionID binds and validates parameter PetitionID from path.
func (o *PetitionsDeleteParams) bindPetitionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("petitionId", "path", "int64", raw)
	}
	o.PetitionID = value

	return nil
}
