// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"jobTask/models"
)

// PetitionsGetByIDOKCode is the HTTP code returned for type PetitionsGetByIDOK
const PetitionsGetByIDOKCode int = 200

/*PetitionsGetByIDOK OK

swagger:response petitionsGetByIdOK
*/
type PetitionsGetByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Petition `json:"body,omitempty"`
}

// NewPetitionsGetByIDOK creates PetitionsGetByIDOK with default headers values
func NewPetitionsGetByIDOK() *PetitionsGetByIDOK {

	return &PetitionsGetByIDOK{}
}

// WithPayload adds the payload to the petitions get by Id o k response
func (o *PetitionsGetByIDOK) WithPayload(payload *models.Petition) *PetitionsGetByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the petitions get by Id o k response
func (o *PetitionsGetByIDOK) SetPayload(payload *models.Petition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PetitionsGetByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
