// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"jobTask/models"
)

// PetitionsDeleteHandlerFunc turns a function with the right signature into a petitions delete handler
type PetitionsDeleteHandlerFunc func(PetitionsDeleteParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PetitionsDeleteHandlerFunc) Handle(params PetitionsDeleteParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PetitionsDeleteHandler interface for that can handle valid petitions delete params
type PetitionsDeleteHandler interface {
	Handle(PetitionsDeleteParams, *models.Principal) middleware.Responder
}

// NewPetitionsDelete creates a new http.Handler for the petitions delete operation
func NewPetitionsDelete(ctx *middleware.Context, handler PetitionsDeleteHandler) *PetitionsDelete {
	return &PetitionsDelete{Context: ctx, Handler: handler}
}

/* PetitionsDelete swagger:route DELETE /petitions/{petitionId} petitions petitionsDelete

Remove a petition

*/
type PetitionsDelete struct {
	Context *middleware.Context
	Handler PetitionsDeleteHandler
}

func (o *PetitionsDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPetitionsDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
