// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"jobTask/models"
)

// PetitionsGetOKCode is the HTTP code returned for type PetitionsGetOK
const PetitionsGetOKCode int = 200

/*PetitionsGetOK OK

swagger:response petitionsGetOK
*/
type PetitionsGetOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Petition `json:"body,omitempty"`
}

// NewPetitionsGetOK creates PetitionsGetOK with default headers values
func NewPetitionsGetOK() *PetitionsGetOK {

	return &PetitionsGetOK{}
}

// WithPayload adds the payload to the petitions get o k response
func (o *PetitionsGetOK) WithPayload(payload []*models.Petition) *PetitionsGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the petitions get o k response
func (o *PetitionsGetOK) SetPayload(payload []*models.Petition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PetitionsGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Petition, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
