// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"jobTask/models"
)

// PetitionsPostHandlerFunc turns a function with the right signature into a petitions post handler
type PetitionsPostHandlerFunc func(PetitionsPostParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PetitionsPostHandlerFunc) Handle(params PetitionsPostParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PetitionsPostHandler interface for that can handle valid petitions post params
type PetitionsPostHandler interface {
	Handle(PetitionsPostParams, *models.Principal) middleware.Responder
}

// NewPetitionsPost creates a new http.Handler for the petitions post operation
func NewPetitionsPost(ctx *middleware.Context, handler PetitionsPostHandler) *PetitionsPost {
	return &PetitionsPost{Context: ctx, Handler: handler}
}

/* PetitionsPost swagger:route POST /petitions petitions petitionsPost

Create a new petition

*/
type PetitionsPost struct {
	Context *middleware.Context
	Handler PetitionsPostHandler
}

func (o *PetitionsPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPetitionsPostParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
