// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"jobTask/models"
)

// PetitionsUpdateOKCode is the HTTP code returned for type PetitionsUpdateOK
const PetitionsUpdateOKCode int = 200

/*PetitionsUpdateOK OK

swagger:response petitionsUpdateOK
*/
type PetitionsUpdateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Petition `json:"body,omitempty"`
}

// NewPetitionsUpdateOK creates PetitionsUpdateOK with default headers values
func NewPetitionsUpdateOK() *PetitionsUpdateOK {

	return &PetitionsUpdateOK{}
}

// WithPayload adds the payload to the petitions update o k response
func (o *PetitionsUpdateOK) WithPayload(payload *models.Petition) *PetitionsUpdateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the petitions update o k response
func (o *PetitionsUpdateOK) SetPayload(payload *models.Petition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PetitionsUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
