// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"jobTask/models"
)

// PetitionsGetByIDHandlerFunc turns a function with the right signature into a petitions get by Id handler
type PetitionsGetByIDHandlerFunc func(PetitionsGetByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PetitionsGetByIDHandlerFunc) Handle(params PetitionsGetByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PetitionsGetByIDHandler interface for that can handle valid petitions get by Id params
type PetitionsGetByIDHandler interface {
	Handle(PetitionsGetByIDParams, *models.Principal) middleware.Responder
}

// NewPetitionsGetByID creates a new http.Handler for the petitions get by Id operation
func NewPetitionsGetByID(ctx *middleware.Context, handler PetitionsGetByIDHandler) *PetitionsGetByID {
	return &PetitionsGetByID{Context: ctx, Handler: handler}
}

/* PetitionsGetByID swagger:route GET /petitions/{petitionId} petitions petitionsGetById

Get a petition

*/
type PetitionsGetByID struct {
	Context *middleware.Context
	Handler PetitionsGetByIDHandler
}

func (o *PetitionsGetByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPetitionsGetByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
