// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"jobTask/models"
)

// PetitionsDeleteOKCode is the HTTP code returned for type PetitionsDeleteOK
const PetitionsDeleteOKCode int = 200

/*PetitionsDeleteOK OK

swagger:response petitionsDeleteOK
*/
type PetitionsDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.Petition `json:"body,omitempty"`
}

// NewPetitionsDeleteOK creates PetitionsDeleteOK with default headers values
func NewPetitionsDeleteOK() *PetitionsDeleteOK {

	return &PetitionsDeleteOK{}
}

// WithPayload adds the payload to the petitions delete o k response
func (o *PetitionsDeleteOK) WithPayload(payload *models.Petition) *PetitionsDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the petitions delete o k response
func (o *PetitionsDeleteOK) SetPayload(payload *models.Petition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PetitionsDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
