// Code generated by go-swagger; DO NOT EDIT.

package petitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"jobTask/models"
)

// PetitionsGetHandlerFunc turns a function with the right signature into a petitions get handler
type PetitionsGetHandlerFunc func(PetitionsGetParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PetitionsGetHandlerFunc) Handle(params PetitionsGetParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PetitionsGetHandler interface for that can handle valid petitions get params
type PetitionsGetHandler interface {
	Handle(PetitionsGetParams, *models.Principal) middleware.Responder
}

// NewPetitionsGet creates a new http.Handler for the petitions get operation
func NewPetitionsGet(ctx *middleware.Context, handler PetitionsGetHandler) *PetitionsGet {
	return &PetitionsGet{Context: ctx, Handler: handler}
}

/* PetitionsGet swagger:route GET /petitions petitions petitionsGet

Get all petitions

*/
type PetitionsGet struct {
	Context *middleware.Context
	Handler PetitionsGetHandler
}

func (o *PetitionsGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPetitionsGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
