// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Petition petition
//
// swagger:model petition
type Petition struct {

	// Email address of the author of the petition
	// Example: silent_man@email.com
	AuthorEmail string `json:"author_email,omitempty"`

	// Body of the petition
	// Example: My neighbors are very loud
	Body string `json:"body,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Name of the petition
	// Example: Loud neighbors
	Name string `json:"name,omitempty"`
}

// Validate validates this petition
func (m *Petition) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this petition based on the context it is used
func (m *Petition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Petition) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Petition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Petition) UnmarshalBinary(b []byte) error {
	var res Petition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
